2019-08-07 20:18:51,177 ERROR: Exception on /dashboard [GET] [in c:\users\bkettle\onedrive\documents\development\proj\homie\venv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\users\bkettle\onedrive\documents\development\proj\homie\venv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\bkettle\onedrive\documents\development\proj\homie\venv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\bkettle\onedrive\documents\development\proj\homie\venv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\bkettle\onedrive\documents\development\proj\homie\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\users\bkettle\onedrive\documents\development\proj\homie\venv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\bkettle\onedrive\documents\development\proj\homie\venv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\bkettle\onedrive\documents\development\proj\homie\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\bkettle\onedrive\documents\development\proj\homie\app\routes.py", line 125, in dashboard
    return render_template('dashboard.html', user=current_user, homes=homes)
  File "c:\users\bkettle\onedrive\documents\development\proj\homie\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\bkettle\onedrive\documents\development\proj\homie\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\bkettle\onedrive\documents\development\proj\homie\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\bkettle\onedrive\documents\development\proj\homie\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\bkettle\onedrive\documents\development\proj\homie\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\bkettle\onedrive\documents\development\proj\homie\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\bkettle\onedrive\documents\development\proj\homie\app\templates\dashboard.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\bkettle\onedrive\documents\development\proj\homie\app\templates\base.html", line 2, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\bkettle\onedrive\documents\development\proj\homie\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\bkettle\onedrive\documents\development\proj\homie\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\bkettle\onedrive\documents\development\proj\homie\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\bkettle\onedrive\documents\development\proj\homie\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\bkettle\onedrive\documents\development\proj\homie\app\templates\base.html", line 46, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\bkettle\onedrive\documents\development\proj\homie\app\templates\dashboard.html", line 13, in block "app_content"
    {% include '_home.html' %}
  File "C:\Users\bkettle\onedrive\documents\development\proj\homie\app\templates\_home.html", line 4, in top-level template code
    <a href="{{ url_for('home', home_url=home.url) }}">
  File "c:\users\bkettle\onedrive\documents\development\proj\homie\venv\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\bkettle\onedrive\documents\development\proj\homie\venv\lib\site-packages\flask\app.py", line 2080, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\bkettle\onedrive\documents\development\proj\homie\venv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\users\bkettle\onedrive\documents\development\proj\homie\venv\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "c:\users\bkettle\onedrive\documents\development\proj\homie\venv\lib\site-packages\werkzeug\routing.py", line 2007, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'home'. Did you forget to specify values ['home_url']?
